CLASSPATH+=:/usr/share/java/junit.jar:../../antlr-2.7.5.jar:../../JavaComplex.jar:../../stringtemplate.jar:../../colt.jar:../../commons-collections-3.1.jar:../../jung-1.7.1.jar:../../epsgraphics.jar:../../:/usr/local/maple10/java/jopenmaple.jar:/usr/local/maple10/java/externalcall.jar

ALLOBJECTS=EAST.class SubprogramAST.class Variable.class Function.class StatementFunction.class


all: $(ALLOBJECTS)

EAST.class: EAST.java
	$(JAVAC) EAST.java
SubprogramAST.class: SubprogramAST.java
	$(JAVAC) SubprogramAST.java
Variable.class: Variable.java
	$(JAVAC) Variable.java
Function.class: Function.java
	$(JAVAC) Function.java
StatementFunction.class: StatementFunction.java
	$(JAVAC) StatementFunction.java
